services:
    
  web: 
    container_name: myapp2-php
    build: ./docker-config/php
    ports:
      - '5173:5173'
    volumes:
      - ./my-app:/var/www/

  nginx:
    container_name: myapp2-nginx
    image: nginx
    build: ./docker-config/nginx
    ports:
      - "80:80"
    volumes:
      - ./my-app:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
